config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"
  get "about", to: "pages#about"

  get "login", to: "pages#new_login"
  post "login", to: "pages#process_login"

  get "logout", to: "pages#logout"

  resources :admins
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
	has_many :seats
	
	validates :departure, presence: true
	validates :arrival, presence: true
	validates :destination, presence: true
	validates :baggage, presence: true, numericality: {greater_than: -1}
	validates :capacity, presence: true, numericality: {only_integer: true, greater_than: 0}



end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # trigger action before executing your functions
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:departure, :arrival, :destination, :baggage, :capacity)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_list_seat.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table class="table table-bordered">
  <thead>
    <tr align="center">
      <th>Name</th>
      <th>Baggage</th>
      <th>Flight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!-- remove @ sign while using partial -->
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.name %></td>
        <td align="center"><%= seat.baggage %></td>
        <td align="center"><%= seat.flight_id %></td>
        <td>
           <button class="btn btn-outline-warning btn-block"> 
              <%= link_to 'Show', seat %>
           </button>
        </td>
        <td>
           <button class="btn btn-outline-success btn-block"> 
              <%= link_to 'Edit', edit_seat_path(seat) %>
           </button>
        </td>
        <td>
          <button class="btn btn-outline-danger btn-block"> 
            <%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/_new_seat.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1> Add Seat </h1>

<div class="row">
  <div class="col-sm-4">
        <div class="card">
          <div class="card-body">

          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :baggage %>
            <%= form.text_field :baggage, class: "form-control" %>
          </div>

          <%= form.hidden_field :flight_id, value: f_id%>

          <div class="actions">
            <%= form.submit :Add, class: "btn btn-warning btn-block" %>
          </div>
        <% end %>
        </div>
    </div>
  </div>
</div>

<br>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table class="table table-bordered">
  <thead>
    <tr align="center">
      <th>Departure</th>
      <th>Arrival</th>
      <th>Destination</th>
      <th>Baggage</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr align="center">
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.baggage %></td>
        <td><%= flight.capacity %></td>
        <td>
        <button class="btn btn-outline-warning btn-block">
          <%= link_to 'Show', flight %>
        </button>
        </td>
        <td>
        <button class="btn btn-outline-success btn-block">
          <%= link_to 'Edit', edit_flight_path(flight) %>
        </button>
        </td>
        <td>
        <button class="btn btn-outline-danger btn-block">
          <%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %>
        </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/flights/new">
<button class="btn btn-outline-primary">
New Flight
</button>
</a>

</div>

app/views/flights/new.html.erb
<div class="container">
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>
</div>

app/views/flights/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Flight Details</h1>

<table class="table table-bordered">
  <tr align="center">
    <th> Departure </th>
    <th> Arrival </th>
    <th> Destination </th>
    <th> Baggage Allowance </th>
    <th> Capacity </th>
    <th> </th>
  </tr>
  <tr align="center">
    <td> <%= @flight.departure %> </td>
    <td> <%= @flight.arrival %> </td>
    <td> <%= @flight.destination %> </td>
    <td> <%= @flight.baggage %> </td>
    <td> <%= @flight.capacity %> </td>
    <td>
      <button class="btn btn-outline-success btn-block"> 
        <%= link_to 'Edit', edit_flight_path(@flight) %> 
      </button>
    </td>
  </tr>
</table>



<%= render "list_seat", seats: @flight.seats %>

<br>

<%= render "new_seat", seat: Seat.new, f_id: @flight.id %>

</div>